const NUTRYFIT_BOWL_LOW = [
  { label: "Chico · 120 g", price: 155 },
  { label: "Mediano · 150 g", price: 220 },
  { label: "Grande · 240 g", price: 270 },
];

const NUTRYFIT_BOWL_HIGH = [
  { label: "Chico · 120 g", price: 175 },
  { label: "Mediano · 150 g", price: 245 },
  { label: "Grande · 240 g", price: 330 },
];

const NUTRYFIT_COLD_BAR = [
  "Edamames",
  "Panela",
  "Zanahoria",
  "Pimiento",
  "Elote",
  "Brócoli",
  "Manzana verde",
  "Tomate cherry",
  "Espinaca",
  "Champiñón",
  "Cebolla morada",
  "Aguacate",
  "Philadelphia",
  "Mango por temporada",
  "Fresa por temporada",
];

const NUTRYFIT_BOWL_ADDONS = [
  {
    id: "portion-adjustments",
    label: "Ajustes de porción",
    note: "Nutryfit confirmará el cargo de estos ajustes por WhatsApp.",
    options: [
      { id: "double-base", label: "Doble base", price: null },
      { id: "double-protein", label: "Doble proteína", price: null },
    ],
  },
  {
    id: "cold-bar-extras",
    label: "Toppings extra de barra fría",
    note: "Selecciona exactamente cuáles deseas. Cada uno suma $20.",
    options: NUTRYFIT_COLD_BAR.map((label) => ({ id: `cold-${label}`, label, price: 20 })),
  },
  {
    id: "bowl-extras",
    label: "Extras de poke o ensalada",
    options: [
      { id: "pollo-extra", label: "Pollo · 60 g", price: 30 },
      { id: "tampico-extra", label: "Tampico · 60 g", price: 25 },
      { id: "atun-extra", label: "Atún · 60 g", price: 45 },
      { id: "camaron-extra", label: "Camarón · 60 g", price: 45 },
      { id: "salmon-extra", label: "Salmón · 60 g", price: 45 },
      { id: "aderezo-extra", label: "Aderezo extra", price: 15 },
    ],
  },
];

const NUTRYFIT_MILKS = {
  id: "milk",
  label: "Elige tu tipo de leche",
  required: true,
  single: true,
  options: [
    { label: "Entera", price: 0 },
    { label: "Deslactosada", price: 0 },
    { label: "Almendras", price: 0, pricesByOption: { "16 oz": 15, "32 oz": 30 } },
    { label: "Coco", price: 0, pricesByOption: { "16 oz": 15, "32 oz": 30 } },
  ],
};

const NUTRYFIT_SANDWICH_ADDONS = [
  {
    id: "sandwich-extras",
    label: "Ingredientes extra",
    options: [
      { label: "Huevo · 1 pza", price: 15 },
      { label: "Clara · 1 pza", price: 10 },
      { label: "Claras · 2 pzas", price: 20 },
      { label: "Jamón · 1 rebanada", price: 10 },
      { label: "Pollo · 60 g", price: 30 },
      { label: "Panela · 40 g", price: 20 },
      { label: "Aguacate · 1/4 pza", price: 20 },
    ],
  },
];

const NUTRYFIT_DRINK_SIZES = [
  { label: "16 oz", price: 50 },
  { label: "32 oz", price: 70 },
];

const NUTRYFIT_SMOOTHIE_SIZES = [
  { label: "16 oz", price: 55 },
  { label: "32 oz", price: 75 },
];

window.NUTRYFIT_DATA = {
  business: {
    name: "NUTRYFIT",
    description: "Nutrición y comida saludable",
    whatsapp: "526441541732",
    phone: "(644) 154 1732",
    branch: "Nutryfit Centro",
    address: "Av. No Reelección 101, local 3, Col. Centro.",
    hours: "Lunes a sábado, de 7:00 a. m. a 6:00 p. m.",
    timezone: "America/Hermosillo",
  },
  gallery: [
    { image: "./FOTOS/1.png", alt: "Bowl Nutryfit con aderezo" },
    { image: "./FOTOS/2.png", alt: "Selección de alimentos Nutryfit" },
    { image: "./FOTOS/3.png", alt: "Bowl con aguacate y mango" },
    { image: "./FOTOS/4.png", alt: "Poke colorido Nutryfit" },
    { image: "./FOTOS/5.png", alt: "Bowl cremoso Nutryfit" },
    { image: "./FOTOS/6.png", alt: "Poke servido en mesa" },
  ],
  categories: [
    {
      id: "build-poke",
      name: "Arma tu bowl",
      tagline: "7 pasos, exactamente a tu gusto",
      image: "./assets/menu/poke-caribeno.webp",
      icon: "sliders-horizontal",
    },
    {
      id: "eggs",
      name: "Huevos",
      tagline: "Omelettes y huevos al gusto",
      image: "./assets/menu/omelette.webp",
      icon: "egg-fried",
    },
    {
      id: "sandwiches",
      name: "Sándwich & Toast",
      tagline: "Pan integral de granos y aderezo especial",
      image: "./assets/menu/sandwich-de-pollo.webp",
      icon: "sandwich",
    },
    {
      id: "chilaquiles",
      name: "Chilaquiles",
      tagline: "En salsa verde o roja",
      image: "./assets/menu/chilaquiles-sencillos.webp",
      icon: "cooking-pot",
    },
    {
      id: "pokes",
      name: "Pokes",
      tagline: "Combinaciones frescas en tres tamaños",
      image: "./assets/menu/tuna-mango.webp",
      icon: "circle-dot",
    },
    {
      id: "salads",
      name: "Ensaladas",
      tagline: "Bowls frescos, completos y crujientes",
      image: "./assets/menu/ensalada-vital.webp",
      icon: "leaf",
    },
    {
      id: "more",
      name: "Más opciones",
      tagline: "Fruta, burritos y opciones ligeras",
      image: "./assets/menu/burritos-de-avena-e-integrales.webp",
      icon: "utensils",
    },
    {
      id: "sweet",
      name: "Lo dulce",
      tagline: "Hot cakes, pan crema y overnight oats",
      image: "./assets/menu/hot-cakes-de-avena.webp",
      icon: "sparkles",
    },
    {
      id: "juices",
      name: "Jugos",
      tagline: "Once mezclas naturales en dos tamaños",
      image: "./assets/menu/94d5f1e6-495a-4546-bd59-9a1ba35556a8.webp",
      icon: "citrus",
    },
    {
      id: "smoothies",
      name: "Licuados",
      tagline: "Mezclas cremosas y personalizables",
      image: "./assets/menu/e18f8e35-5120-4981-a144-4a12a9fa26e5.webp",
      icon: "cup-soda",
    },
    {
      id: "drinks",
      name: "Bebidas & Café",
      tagline: "Jamaica, limonadas, sparkling y café",
      image: "./assets/menu/jamaica.webp",
      icon: "coffee",
    },
  ],
  products: [
    {
      id: "custom-poke",
      categoryId: "build-poke",
      name: "Arma tu bowl o ensalada",
      description: "Elige tamaño, base, proteína, ingredientes, aderezos, crocante y extras.",
      image: "./assets/menu/poke-caribeno.webp",
      priceFrom: 155,
      badge: "Personalizable",
      configurable: true,
    },

    {
      id: "omelette",
      categoryId: "eggs",
      name: "Omelette",
      description:
        "Omelette de 2 huevos relleno de pimiento, espinaca, queso Oaxaca y jamón. Acompañado de ensalada, frijol, salsa y 1 pieza de pan integral tostado.",
      image: "./assets/menu/omelette.webp",
      price: 120,
    },
    {
      id: "omelette-fit",
      categoryId: "eggs",
      name: "Omelette Fit",
      description:
        "Omelette de claras de huevo, relleno de salsa bandera y queso panela. Acompañado de ensalada y 1 pieza de pan integral tostado.",
      image: "./assets/menu/omelette-fit.webp",
      price: 130,
    },
    {
      id: "huevos-al-gusto",
      categoryId: "eggs",
      name: "Huevos al gusto",
      description:
        "2 huevos con un ingrediente a elegir. Acompañados de frijol natural y tu elección de 2 tortillas de maíz o 1 pieza de pan integral.",
      image: "./assets/menu/huevos-al-gusto.webp",
      price: 110,
      choiceLabel: "Elige el ingrediente",
      choices: [
        "Machaca con verdura",
        "Nopal",
        "Pimiento",
        "Chorizo",
        "Chorizo de soya",
        "Jamón",
        "Verdura",
        "Espinaca",
      ],
      addonGroups: [
        {
          id: "egg-extra",
          label: "Ingrediente extra",
          options: [
            { label: "Huevo · 1 pza", price: 15 },
            { label: "Clara · 1 pza", price: 10 },
            { label: "Claras · 2 pzas", price: 20 },
          ],
        },
      ],
    },

    {
      id: "sandwich-clasico",
      categoryId: "sandwiches",
      name: "Sándwich clásico",
      description: "Jamón de pavo, queso americano, lechuga, tomate, alfalfa y aguacate.",
      image: "./assets/menu/sandwich-clasico.webp",
      price: 50,
      addonGroups: NUTRYFIT_SANDWICH_ADDONS,
    },
    {
      id: "sandwich-jamon-panela",
      categoryId: "sandwiches",
      name: "Sándwich de jamón con panela",
      description: "Jamón de pavo, panela, lechuga, tomate, alfalfa y aguacate.",
      image: "./assets/menu/sandwich-jamon-panela.webp",
      price: 55,
      addonGroups: NUTRYFIT_SANDWICH_ADDONS,
    },
    {
      id: "sandwich-huevo-panela",
      categoryId: "sandwiches",
      name: "Sándwich de huevo con panela asada",
      description: "Huevo en torta, queso panela, espinaca, tomate, alfalfa y aguacate.",
      image: "./assets/menu/sandwich-jamon-panela.webp",
      price: 70,
      addonGroups: NUTRYFIT_SANDWICH_ADDONS,
    },
    {
      id: "sandwich-pollo",
      categoryId: "sandwiches",
      name: "Sándwich de pollo",
      description: "Pechuga de pollo a la plancha, queso Oaxaca gratinado, lechuga, alfalfa, tomate y aguacate.",
      image: "./assets/menu/sandwich-de-pollo.webp",
      price: 80,
      addonGroups: NUTRYFIT_SANDWICH_ADDONS,
    },
    {
      id: "sandwich-atun",
      categoryId: "sandwiches",
      name: "Sándwich de atún",
      description: "Atún cremoso con chipotle, lechuga, alfalfa, tomate y aguacate.",
      image: "./assets/menu/sandwich-de-atun.webp",
      price: 70,
      addonGroups: NUTRYFIT_SANDWICH_ADDONS,
    },
    {
      id: "avocado-egg-toast",
      categoryId: "sandwiches",
      name: "Avocado Egg Toast",
      description: "Pan integral tostado con aguacate, huevo estrellado o revuelto y tomate cherry.",
      image: "./assets/menu/abocado-toast.webp",
      price: 60,
      choiceLabel: "Elige tu huevo",
      choices: ["Estrellado", "Revuelto"],
    },
    {
      id: "panela-toast",
      categoryId: "sandwiches",
      name: "Panela Toast",
      description: "Pan integral tostado con aguacate, espinaca, panela asada y tomate cherry.",
      image: "./assets/menu/abocado-toast.webp",
      price: 55,
    },
    {
      id: "molletes",
      categoryId: "sandwiches",
      name: "Molletes",
      description: "2 molletes de pan integral con frijol natural, queso Oaxaca y jamón. Acompañados de salsa bandera.",
      image: "./assets/menu/molletes.webp",
      price: 80,
    },

    {
      id: "chilaquiles",
      categoryId: "chilaquiles",
      name: "Chilaquiles",
      description:
        "En salsa verde o roja con queso Oaxaca gratinado, cebolla y cilantro. Acompañados de frijol natural y ensalada; opcional con totopos horneados.",
      image: "./assets/menu/chilaquiles-sencillos.webp",
      choiceLabel: "Elige la salsa",
      choices: ["Salsa verde", "Salsa roja"],
      priceOptions: [
        { label: "Sencillos", price: 120, image: "./assets/menu/chilaquiles-sencillos.webp" },
        { label: "Con huevo", price: 135, image: "./assets/menu/chilaquiles-con-huevo.webp" },
        { label: "Con pollo", price: 145, image: "./assets/menu/chilaquiles-con-pollo.webp" },
      ],
      addonGroups: [
        {
          id: "chilaquiles-extras",
          label: "Ingredientes extra",
          options: [
            { label: "Huevo · 1 pza", price: 15 },
            { label: "Clara · 1 pza", price: 10 },
            { label: "Claras · 2 pzas", price: 20 },
            { label: "Pollo · 60 g", price: 30 },
            { label: "Frijol · 4 oz", price: 15 },
            { label: "Aguacate · 1/4 pza", price: 20 },
            { label: "Panela · 40 g", price: 20 },
            { label: "Crema · 2 oz", price: 10 },
            { label: "Salsa · 4 oz", price: 15 },
          ],
        },
      ],
    },

    {
      id: "tropical-shrimp",
      categoryId: "pokes",
      name: "Tropical Shrimp",
      description:
        "Arroz, camarón, mango, pimiento, zanahoria y aguacate; spicy mayo, sriracha, anguila y tiras de maíz.",
      image: "./assets/menu/tropical-shrimp.webp",
      priceOptions: NUTRYFIT_BOWL_HIGH,
      addonGroups: NUTRYFIT_BOWL_ADDONS,
    },
    {
      id: "caribeno",
      categoryId: "pokes",
      name: "Caribeño",
      description:
        "Noodles de pepino y quinoa, salmón, arándano, manzana verde, aguacate y zanahoria; frutos rojos y tiras de maíz.",
      image: "./assets/menu/poke-caribeno.webp",
      priceOptions: NUTRYFIT_BOWL_HIGH,
      addonGroups: NUTRYFIT_BOWL_ADDONS,
    },
    {
      id: "tuna-mango",
      categoryId: "pokes",
      name: "Tuna Mango",
      description:
        "Arroz, medallón de atún y tampico, mango, edamames, zanahoria y aguacate; chipotle, anguila y wonton.",
      image: "./assets/menu/tuna-mango.webp",
      priceOptions: NUTRYFIT_BOWL_HIGH,
      addonGroups: NUTRYFIT_BOWL_ADDONS,
    },
    {
      id: "chicken-buffalo",
      categoryId: "pokes",
      name: "Chicken Buffalo",
      description:
        "Arroz, pollo buffalo, brócoli, zanahoria, arándano y Philadelphia; chipotle, ranch y crutones.",
      image: "./assets/menu/poke-chicken-buffalo.webp",
      priceOptions: NUTRYFIT_BOWL_LOW,
      addonGroups: NUTRYFIT_BOWL_ADDONS,
    },
    {
      id: "tampico-crunch",
      categoryId: "pokes",
      name: "Tampico Crunch",
      description: "Arroz, tampico, pepino, pimiento y elote; aderezo chipotle y crutones.",
      image: "./assets/menu/tampico-crush.webp",
      priceOptions: NUTRYFIT_BOWL_LOW,
      addonGroups: NUTRYFIT_BOWL_ADDONS,
    },

    {
      id: "ensalada-vital",
      categoryId: "salads",
      name: "Ensalada Vital",
      description:
        "Lechuga orejona, pollo mostaza miel, pepino, tomate cherry, panela y aceitunas; chipotle y crutones.",
      image: "./assets/menu/ensalada-vital.webp",
      priceOptions: [
        { label: "Chico · 120 g", price: 155 },
        { label: "Mediano · 150 g", price: 245 },
        { label: "Grande · 240 g", price: 270 },
      ],
      addonGroups: NUTRYFIT_BOWL_ADDONS,
    },
    {
      id: "tropical-glow",
      categoryId: "salads",
      name: "Tropical Glow",
      description:
        "Mix de lechugas, pollo mostaza miel, mango, aguacate, zanahoria y arándano; frutos rojos y tiras de maíz.",
      image: "./assets/menu/tropical-glow.webp",
      priceOptions: [
        { label: "Chico · 120 g", price: 155 },
        { label: "Mediano · 150 g", price: 245 },
        { label: "Grande · 240 g", price: 330 },
      ],
      addonGroups: NUTRYFIT_BOWL_ADDONS,
    },
    {
      id: "ensalada-pollo-buffalo",
      categoryId: "salads",
      name: "Ensalada fresca de pollo buffalo",
      description:
        "Mix de lechugas, pollo buffalo, zanahoria, champiñón y aguacate; ranch y tiras de maíz.",
      image: "./assets/menu/ensalada-buffalo.webp",
      priceOptions: [
        { label: "Chico · 120 g", price: 155 },
        { label: "Mediano · 150 g", price: 245 },
        { label: "Grande · 240 g", price: 330 },
      ],
      addonGroups: NUTRYFIT_BOWL_ADDONS,
    },
    {
      id: "dulce-power",
      categoryId: "salads",
      name: "Dulce & Power",
      description:
        "Lechuga y quinoa, atún fresco o salmón, fruta de temporada, aguacate, panela y tomate cherry; frutos rojos y tiras de maíz.",
      image: "./assets/menu/dulce-and-power.webp",
      choiceLabel: "Elige tu proteína",
      choices: ["Atún fresco", "Salmón"],
      priceOptions: NUTRYFIT_BOWL_HIGH,
      addonGroups: NUTRYFIT_BOWL_ADDONS,
    },
    {
      id: "ensalada-mediterranea",
      categoryId: "salads",
      name: "Ensalada Mediterránea",
      description:
        "Pollo mostaza miel, lechuga orejona, pepino, tomate cherry, alfalfa, fruta de temporada y panela; crutones y chipotle.",
      image: "./assets/menu/ensalada-mediterranea.webp",
      price: 155,
      addonGroups: NUTRYFIT_BOWL_ADDONS,
    },

    {
      id: "fruta-yogurt",
      categoryId: "more",
      name: "Fruta con yogurt",
      description: "Papaya, plátano, manzana, melón, fresa de temporada, yogurt natural, granola y miel.",
      image: "./assets/menu/fruta-con-yogurt.webp",
      price: 65,
    },
    {
      id: "fruta-tajin",
      categoryId: "more",
      name: "Fruta picada con Tajín y limón",
      description: "Piña, jícama, pepino, naranja o mango de temporada.",
      image: "./assets/menu/fruta-picada.webp",
      price: 50,
    },
    {
      id: "burritos-integral",
      categoryId: "more",
      name: "Burritos en tortilla integral",
      description: "3 piezas de machaca con verdura, papas con chorizo o frijol. Acompañados de ensalada.",
      image: "./assets/menu/burritos-de-avena-e-integrales.webp",
      price: 80,
      choiceLabel: "Elige el relleno",
      choices: ["Machaca con verdura", "Papas con chorizo", "Frijol"],
    },
    {
      id: "burritos-avena",
      categoryId: "more",
      name: "Burritos en tortilla de avena",
      description: "3 piezas de machaca con verdura, papas con chorizo o frijol. Acompañados de ensalada.",
      image: "./assets/menu/burritos-de-avena-e-integrales.webp",
      price: 95,
      choiceLabel: "Elige el relleno",
      choices: ["Machaca con verdura", "Papas con chorizo", "Frijol"],
    },

    {
      id: "hotcakes",
      categoryId: "sweet",
      name: "Hot Cakes de Avena",
      description: "Acompañados de kiwi, fresa, plátano y miel.",
      image: "./assets/menu/hot-cakes-de-avena.webp",
      price: 120,
      addonGroups: [
        {
          id: "hotcakes-extras",
          label: "Ingredientes extra",
          options: [
            { label: "Miel · 1 oz", price: 15 },
            { label: "Crema de cacahuate · 1 oz", price: 15 },
          ],
        },
      ],
    },
    {
      id: "pan-crema",
      categoryId: "sweet",
      name: "Pan Crema",
      description: "Pan integral con crema de cacahuate, plátano y fresa de temporada.",
      image: "./assets/menu/pan-crema.webp",
      price: 50,
    },
    {
      id: "overnight-apple",
      categoryId: "sweet",
      name: "Overnight Oats Apple Pie",
      description:
        "Avena con leche deslactosada, yogurt, vainilla y canela; chía pudding, manzana verde y crema de cacahuate.",
      image: "./assets/menu/apple-pie.webp",
      price: 70,
    },
    {
      id: "overnight-choco",
      categoryId: "sweet",
      name: "Overnight Oats Choco Berry",
      description:
        "Avena cremosa con cocoa, fresa, plátano, chocolate líquido y coco rallado.",
      image: "./assets/menu/chocoberry.webp",
      price: 70,
    },
    {
      id: "overnight-green",
      categoryId: "sweet",
      name: "Overnight Oats Green Boost",
      description:
        "Avena con matcha orgánico y chía pudding; fresa, plátano, arándanos y granola.",
      image: "./assets/menu/greenboost.webp",
      price: 70,
    },

    {
      id: "jugos",
      categoryId: "juices",
      name: "Jugos naturales",
      description: "Elige tu mezcla favorita y el tamaño.",
      image: "./assets/menu/94d5f1e6-495a-4546-bd59-9a1ba35556a8.webp",
      choiceLabel: "Elige tu jugo",
      choices: [
        "Verde Vital",
        "Red Power Boost",
        "Red Fresh",
        "Hierro Power",
        "Sunrise",
        "Antioxidante",
        "Antigripal",
        "Pink Boost",
        "Zana-ranja",
        "Naranja natural",
        "Betabel con naranja",
      ],
      choiceImages: {
        "Verde Vital": "./assets/menu/jugo-verde.webp",
        "Red Power Boost": "./assets/menu/juego-red-power.webp",
        "Red Fresh": "./assets/menu/jugo-red-fresh.webp",
        "Hierro Power": "./assets/menu/jugo-betabel-naranja.webp",
        "Sunrise": "./assets/menu/jugo-sunrise.webp",
        "Antioxidante": "./assets/menu/jugo-antiosidante.webp",
        "Antigripal": "./assets/menu/94d5f1e6-495a-4546-bd59-9a1ba35556a8.webp",
        "Pink Boost": "./assets/menu/37191f47-9881-4d74-8c3f-252a179067eb.webp",
        "Zana-ranja": "./assets/menu/jugo-de-zanahoria-y-naranja.webp",
        "Naranja natural": "./assets/menu/jugo-de-naranja.webp",
        "Betabel con naranja": "./assets/menu/jugo-betabel-naranja.webp",
      },
      priceOptions: NUTRYFIT_DRINK_SIZES,
    },
    {
      id: "licuado-digestivo",
      categoryId: "smoothies",
      name: "Digestivo",
      description: "Papaya, manzana, canela, vainilla, All Bran, linaza y chía.",
      image: "./assets/menu/e18f8e35-5120-4981-a144-4a12a9fa26e5.webp",
      priceOptions: NUTRYFIT_SMOOTHIE_SIZES,
      addonGroups: [NUTRYFIT_MILKS],
    },
    {
      id: "licuado-mazapan",
      categoryId: "smoothies",
      name: "Mazapán",
      description: "Plátano, espinaca, crema de cacahuate y vainilla.",
      image: "./assets/menu/mazapan.webp",
      priceOptions: NUTRYFIT_SMOOTHIE_SIZES,
      addonGroups: [NUTRYFIT_MILKS],
    },
    {
      id: "licuado-strawberry",
      categoryId: "smoothies",
      name: "Strawberry",
      description: "Fresa, blueberries, arándano y plátano.",
      image: "./assets/menu/strawberry.webp",
      priceOptions: NUTRYFIT_SMOOTHIE_SIZES,
      addonGroups: [NUTRYFIT_MILKS],
    },
    {
      id: "licuado-choco-banana",
      categoryId: "smoothies",
      name: "Choco Banana",
      description: "Cacao, plátano y avena.",
      image: "./assets/menu/chocobanana.webp",
      priceOptions: NUTRYFIT_SMOOTHIE_SIZES,
      addonGroups: [NUTRYFIT_MILKS],
    },
    {
      id: "licuado-fresa-platano",
      categoryId: "smoothies",
      name: "Fresa Plátano",
      description: "Fresa y plátano.",
      image: "./assets/menu/fresa-platano.webp",
      priceOptions: NUTRYFIT_SMOOTHIE_SIZES,
      addonGroups: [NUTRYFIT_MILKS],
    },
    {
      id: "licuado-personalizado",
      categoryId: "smoothies",
      name: "Arma tu licuado",
      description: "Combina frutas, semillas y complementos a tu gusto.",
      image: "./assets/menu/e18f8e35-5120-4981-a144-4a12a9fa26e5.webp",
      priceOptions: NUTRYFIT_SMOOTHIE_SIZES,
      addonGroups: [
        NUTRYFIT_MILKS,
        {
          id: "smoothie-ingredients",
          label: "Elige los ingredientes",
          note: "Selecciona tu combinación; Nutryfit confirmará las cantidades según el tamaño.",
          required: true,
          selectionOnly: true,
          options: [
            "Manzana roja", "Manzana verde", "Papaya", "Melón", "Mango", "Espinaca", "Plátano", "Fresa",
            "Avena", "Chía", "Linaza", "Nuez", "Almendras", "Arándanos", "Cacao", "Chocomilk",
          ].map((label) => ({ label, price: 0 })),
        },
      ],
    },

    {
      id: "jamaica",
      categoryId: "drinks",
      name: "Jamaica",
      description: "Jamaica natural endulzada con Splenda.",
      image: "./assets/menu/jamaica.webp",
      price: 20,
    },
    {
      id: "limonada-pepino",
      categoryId: "drinks",
      name: "Limonada de pepino con chía",
      description: "Pepino, limón y chía, endulzada con Splenda.",
      image: "./assets/menu/limonada.webp",
      price: 25,
    },
    {
      id: "sparkling",
      categoryId: "drinks",
      name: "Sparkling",
      description: "Bebida carbonatada sin azúcar y sin calorías.",
      image: "./assets/menu/37191f47-9881-4d74-8c3f-252a179067eb.webp",
      price: 35,
      choiceLabel: "Elige el sabor",
      choices: ["Frambuesa negra", "Fresa-kiwi", "Naranja-mango"],
    },
    {
      id: "limonada-frutos-rojos",
      categoryId: "drinks",
      name: "Limonada natural de frutos rojos",
      description: "Limonada natural con frutos rojos.",
      image: "./assets/menu/limonada-frutos-rojos.webp",
      priceOptions: [
        { label: "Chica", price: 30 },
        { label: "Grande", price: 50 },
      ],
    },
    {
      id: "coffee",
      categoryId: "drinks",
      name: "Café orgánico con ganoderma",
      description: "Elige entre café negro, café con crema, Cream Coffee o Vita Café.",
      image: "./assets/menu/cafe.webp",
      priceOptions: [
        { label: "Café negro", price: 30 },
        { label: "Café con crema", price: 40 },
        { label: "Cream Coffee", price: 45 },
        { label: "Vita Café", price: 45 },
      ],
    },
  ],
  pokeBuilder: {
    sizes: [
      { id: "small", name: "Chico", grams: "120 g", coldLimit: 3 },
      { id: "medium", name: "Mediano", grams: "150 g", coldLimit: 4 },
      { id: "large", name: "Grande", grams: "240 g", coldLimit: 5 },
    ],
    bases: ["Lechuga orejona", "Arroz", "Quinoa", "Noodles de pepino"],
    proteins: [
      { id: "pollo-mostaza", name: "Pollo mostaza miel", group: 1 },
      { id: "pollo-natural", name: "Pollo natural", group: 1 },
      { id: "pollo-buffalo", name: "Pollo buffalo", group: 1 },
      { id: "tampico", name: "Tampico", group: 1 },
      { id: "atun", name: "Atún", group: 2 },
      { id: "camaron", name: "Camarón", group: 2 },
      { id: "salmon", name: "Salmón", group: 2 },
    ],
    prices: {
      1: { small: 155, medium: 220, large: 270 },
      2: { small: 175, medium: 245, large: 330 },
    },
    coldBar: NUTRYFIT_COLD_BAR,
    dressings: [
      "Ranch",
      "Chipotle",
      "Mostaza miel",
      "Cilantro serrano",
      "Vinagreta balsámica",
      "Frutos rojos",
      "Spicy mayo",
      "Ponzu",
      "Anguila",
      "Cacahuate oriental",
    ],
    crunch: ["Crutones", "Tiritas de maíz", "Tiritas de wonton", "Cebolla caramelizada"],
    extras: [
      { id: "dressing-extra", name: "Aderezo extra", price: 15 },
      { id: "pollo-extra", name: "Pollo 60 g", price: 30 },
      { id: "tampico-extra", name: "Tampico 60 g", price: 25 },
      { id: "atun-extra", name: "Atún 60 g", price: 45 },
      { id: "camaron-extra", name: "Camarón 60 g", price: 45 },
      { id: "salmon-extra", name: "Salmón 60 g", price: 45 },
    ],
  },
};
