const NUTRYFIT_BOWL_LOW = [
  { label: "Chico", price: 155 },
  { label: "Mediano", price: 220 },
  { label: "Grande", price: 270 },
];

const NUTRYFIT_BOWL_HIGH = [
  { label: "Chico", price: 175 },
  { label: "Mediano", price: 245 },
  { label: "Grande", price: 330 },
];

const NUTRYFIT_DRINK_SIZES = [
  { label: "16 oz", price: 50 },
  { label: "32 oz", price: 70 },
];

const NUTRYFIT_SMOOTHIE_SIZES = [
  { label: "16 oz", price: 55 },
  { label: "32 oz", price: 75 },
];

window.NUTRYFIT_DATA = {
  business: {
    name: "NUTRYFIT",
    description: "Nutrición y comida saludable",
    whatsapp: "526441541732",
    phone: "(644) 154 1732",
    branch: "Nutryfit Centro",
    address: "Av. No Reelección 101, local 3, Col. Centro.",
    hours: "Lunes a viernes, de 9:00 a. m. a 2:00 p. m.",
    timezone: "America/Hermosillo",
  },
  gallery: [
    { image: "./FOTOS/1.png", alt: "Bowl Nutryfit con aderezo" },
    { image: "./FOTOS/2.png", alt: "Selección de alimentos Nutryfit" },
    { image: "./FOTOS/3.png", alt: "Bowl con aguacate y mango" },
    { image: "./FOTOS/4.png", alt: "Poke colorido Nutryfit" },
    { image: "./FOTOS/5.png", alt: "Bowl cremoso Nutryfit" },
    { image: "./FOTOS/6.png", alt: "Poke servido en mesa" },
  ],
  categories: [
    {
      id: "build-poke",
      name: "Arma tu bowl",
      tagline: "7 pasos, exactamente a tu gusto",
      image: "./assets/poke-1.png",
      icon: "sliders-horizontal",
    },
    {
      id: "eggs",
      name: "Huevos",
      tagline: "Omelettes y huevos al gusto",
      image: "./assets/omelet-fit.png",
      icon: "egg-fried",
    },
    {
      id: "sandwiches",
      name: "Sándwich & Toast",
      tagline: "Pan integral de granos y aderezo especial",
      image: "./assets/avocado-egg-toast.png",
      icon: "sandwich",
    },
    {
      id: "chilaquiles",
      name: "Chilaquiles",
      tagline: "En salsa verde o roja",
      image: "./FOTOS/2.png",
      icon: "cooking-pot",
    },
    {
      id: "pokes",
      name: "Pokes",
      tagline: "Combinaciones frescas en tres tamaños",
      image: "./assets/tuna-mango.png",
      icon: "circle-dot",
    },
    {
      id: "salads",
      name: "Ensaladas",
      tagline: "Bowls frescos, completos y crujientes",
      image: "./assets/ensalada-vital.png",
      icon: "leaf",
    },
    {
      id: "more",
      name: "Más opciones",
      tagline: "Fruta, burritos y opciones ligeras",
      image: "./FOTOS/5.png",
      icon: "utensils",
    },
    {
      id: "sweet",
      name: "Lo dulce",
      tagline: "Hot cakes, pan crema y overnight oats",
      image: "./assets/hotcakes-avena.png",
      icon: "sparkles",
    },
    {
      id: "juices",
      name: "Jugos",
      tagline: "Once mezclas naturales en dos tamaños",
      image: "./assets/bebidas.png",
      icon: "citrus",
    },
    {
      id: "smoothies",
      name: "Licuados",
      tagline: "Mezclas cremosas y personalizables",
      image: "./assets/bebidas.png",
      icon: "cup-soda",
    },
    {
      id: "drinks",
      name: "Bebidas & Café",
      tagline: "Jamaica, limonadas, sparkling y café",
      image: "./assets/bebidas.png",
      icon: "coffee",
    },
  ],
  products: [
    {
      id: "custom-poke",
      categoryId: "build-poke",
      name: "Arma tu bowl o ensalada",
      description: "Elige tamaño, base, proteína, ingredientes, aderezos, crocante y extras.",
      image: "./assets/poke-1.png",
      priceFrom: 155,
      badge: "Personalizable",
      configurable: true,
    },

    {
      id: "omelette",
      categoryId: "eggs",
      name: "Omelette",
      description:
        "Omelette de 2 huevos relleno de pimiento, espinaca, queso Oaxaca y jamón. Acompañado de ensalada, frijol, salsa y 1 pieza de pan integral tostado.",
      image: "./assets/omelet-fit.png",
      price: 120,
    },
    {
      id: "omelette-fit",
      categoryId: "eggs",
      name: "Omelette Fit",
      description:
        "Omelette de claras de huevo, relleno de salsa bandera y queso panela. Acompañado de ensalada y 1 pieza de pan integral tostado.",
      image: "./assets/omelet-fit.png",
      price: 130,
    },
    {
      id: "huevos-al-gusto",
      categoryId: "eggs",
      name: "Huevos al gusto",
      description:
        "2 huevos con un ingrediente a elegir. Acompañados de frijol natural y tu elección de 2 tortillas de maíz o 1 pieza de pan integral.",
      image: "./assets/omelet-fit.png",
      price: 110,
      choiceLabel: "Elige el ingrediente",
      choices: [
        "Machaca con verdura",
        "Nopal",
        "Pimiento",
        "Chorizo",
        "Chorizo de soya",
        "Jamón",
        "Verdura",
        "Espinaca",
      ],
    },

    {
      id: "sandwich-clasico",
      categoryId: "sandwiches",
      name: "Sándwich clásico",
      description: "Jamón de pavo, queso americano, lechuga, tomate, alfalfa y aguacate.",
      image: "./assets/avocado-egg-toast.png",
      price: 50,
    },
    {
      id: "sandwich-jamon-panela",
      categoryId: "sandwiches",
      name: "Sándwich de jamón con panela",
      description: "Jamón de pavo, panela, lechuga, tomate, alfalfa y aguacate.",
      image: "./assets/avocado-egg-toast.png",
      price: 55,
    },
    {
      id: "sandwich-huevo-panela",
      categoryId: "sandwiches",
      name: "Sándwich de huevo con panela asada",
      description: "Huevo en torta, queso panela, espinaca, tomate, alfalfa y aguacate.",
      image: "./assets/avocado-egg-toast.png",
      price: 70,
    },
    {
      id: "sandwich-pollo",
      categoryId: "sandwiches",
      name: "Sándwich de pollo",
      description: "Pechuga de pollo a la plancha, queso Oaxaca gratinado, lechuga, alfalfa, tomate y aguacate.",
      image: "./assets/avocado-egg-toast.png",
      price: 80,
    },
    {
      id: "sandwich-atun",
      categoryId: "sandwiches",
      name: "Sándwich de atún",
      description: "Atún cremoso con chipotle, lechuga, alfalfa, tomate y aguacate.",
      image: "./assets/avocado-egg-toast.png",
      price: 70,
    },
    {
      id: "avocado-egg-toast",
      categoryId: "sandwiches",
      name: "Avocado Egg Toast",
      description: "Pan integral tostado con aguacate, huevo estrellado o revuelto y tomate cherry.",
      image: "./assets/avocado-egg-toast.png",
      price: 60,
      choiceLabel: "Elige tu huevo",
      choices: ["Estrellado", "Revuelto"],
    },
    {
      id: "panela-toast",
      categoryId: "sandwiches",
      name: "Panela Toast",
      description: "Pan integral tostado con aguacate, espinaca, panela asada y tomate cherry.",
      image: "./assets/avocado-egg-toast.png",
      price: 55,
    },
    {
      id: "molletes",
      categoryId: "sandwiches",
      name: "Molletes",
      description: "2 molletes de pan integral con frijol natural, queso Oaxaca y jamón. Acompañados de salsa bandera.",
      image: "./FOTOS/2.png",
      price: 80,
    },

    {
      id: "chilaquiles",
      categoryId: "chilaquiles",
      name: "Chilaquiles",
      description:
        "En salsa verde o roja con queso Oaxaca gratinado, cebolla y cilantro. Acompañados de frijol natural y ensalada; opcional con totopos horneados.",
      image: "./FOTOS/2.png",
      choiceLabel: "Elige la salsa",
      choices: ["Salsa verde", "Salsa roja"],
      priceOptions: [
        { label: "Sencillos", price: 120 },
        { label: "Con huevo", price: 135 },
        { label: "Con pollo", price: 145 },
      ],
    },

    {
      id: "tropical-shrimp",
      categoryId: "pokes",
      name: "Tropical Shrimp",
      description:
        "Arroz, camarón, mango, pimiento, zanahoria y aguacate; spicy mayo, sriracha, anguila y tiras de maíz.",
      image: "./assets/tropical-shrimp.png",
      priceOptions: NUTRYFIT_BOWL_HIGH,
    },
    {
      id: "caribeno",
      categoryId: "pokes",
      name: "Caribeño",
      description:
        "Noodles de pepino y quinoa, salmón, arándano, manzana verde, aguacate y zanahoria; frutos rojos y tiras de maíz.",
      image: "./assets/caribeno.png",
      priceOptions: NUTRYFIT_BOWL_HIGH,
    },
    {
      id: "tuna-mango",
      categoryId: "pokes",
      name: "Tuna Mango",
      description:
        "Arroz, medallón de atún y tampico, mango, edamames, zanahoria y aguacate; chipotle, anguila y wonton.",
      image: "./assets/tuna-mango.png",
      priceOptions: NUTRYFIT_BOWL_HIGH,
    },
    {
      id: "chicken-buffalo",
      categoryId: "pokes",
      name: "Chicken Buffalo",
      description:
        "Arroz, pollo buffalo, brócoli, zanahoria, arándano y Philadelphia; chipotle, ranch y crutones.",
      image: "./FOTOS/1.png",
      priceOptions: NUTRYFIT_BOWL_LOW,
    },
    {
      id: "tampico-crunch",
      categoryId: "pokes",
      name: "Tampico Crunch",
      description: "Arroz, tampico, pepino, pimiento y elote; aderezo chipotle y crutones.",
      image: "./assets/tampico-crunch.png",
      priceOptions: NUTRYFIT_BOWL_LOW,
    },

    {
      id: "ensalada-vital",
      categoryId: "salads",
      name: "Ensalada Vital",
      description:
        "Lechuga orejona, pollo mostaza miel, pepino, tomate cherry, panela y aceitunas; chipotle y crutones.",
      image: "./assets/ensalada-vital.png",
      priceOptions: [
        { label: "Chico", price: 155 },
        { label: "Mediano", price: 245 },
        { label: "Grande", price: 270 },
      ],
    },
    {
      id: "tropical-glow",
      categoryId: "salads",
      name: "Tropical Glow",
      description:
        "Mix de lechugas, pollo mostaza miel, mango, aguacate, zanahoria y arándano; frutos rojos y tiras de maíz.",
      image: "./assets/tropical-glow.png",
      priceOptions: [
        { label: "Chico", price: 155 },
        { label: "Mediano", price: 245 },
        { label: "Grande", price: 330 },
      ],
    },
    {
      id: "ensalada-pollo-buffalo",
      categoryId: "salads",
      name: "Ensalada fresca de pollo buffalo",
      description:
        "Mix de lechugas, pollo buffalo, zanahoria, champiñón y aguacate; ranch y tiras de maíz.",
      image: "./assets/ensalada-pollo-buffalo.png",
      priceOptions: [
        { label: "Chico", price: 155 },
        { label: "Mediano", price: 245 },
        { label: "Grande", price: 330 },
      ],
    },
    {
      id: "dulce-power",
      categoryId: "salads",
      name: "Dulce & Power",
      description:
        "Lechuga y quinoa, atún fresco o salmón, fruta de temporada, aguacate, panela y tomate cherry; frutos rojos y tiras de maíz.",
      image: "./assets/dulce-power.png",
      choiceLabel: "Elige tu proteína",
      choices: ["Atún fresco", "Salmón"],
      priceOptions: NUTRYFIT_BOWL_HIGH,
    },
    {
      id: "ensalada-mediterranea",
      categoryId: "salads",
      name: "Ensalada Mediterránea",
      description:
        "Pollo mostaza miel, lechuga orejona, pepino, tomate cherry, alfalfa, fruta de temporada y panela; crutones y chipotle.",
      image: "./assets/ensalada-mediterranea.png",
      price: 155,
    },

    {
      id: "fruta-yogurt",
      categoryId: "more",
      name: "Fruta con yogurt",
      description: "Papaya, plátano, manzana, melón, fresa de temporada, yogurt natural, granola y miel.",
      image: "./FOTOS/5.png",
      price: 65,
    },
    {
      id: "fruta-tajin",
      categoryId: "more",
      name: "Fruta picada con Tajín y limón",
      description: "Piña, jícama, pepino, naranja o mango de temporada.",
      image: "./FOTOS/3.png",
      price: 50,
    },
    {
      id: "burritos-integral",
      categoryId: "more",
      name: "Burritos en tortilla integral",
      description: "3 piezas de machaca con verdura, papas con chorizo o frijol. Acompañados de ensalada.",
      image: "./FOTOS/2.png",
      price: 80,
      choiceLabel: "Elige el relleno",
      choices: ["Machaca con verdura", "Papas con chorizo", "Frijol"],
    },
    {
      id: "burritos-avena",
      categoryId: "more",
      name: "Burritos en tortilla de avena",
      description: "3 piezas de machaca con verdura, papas con chorizo o frijol. Acompañados de ensalada.",
      image: "./FOTOS/2.png",
      price: 95,
      choiceLabel: "Elige el relleno",
      choices: ["Machaca con verdura", "Papas con chorizo", "Frijol"],
    },

    {
      id: "hotcakes",
      categoryId: "sweet",
      name: "Hot Cakes de Avena",
      description: "Acompañados de kiwi, fresa, plátano y miel.",
      image: "./assets/hotcakes-avena.png",
      price: 120,
    },
    {
      id: "pan-crema",
      categoryId: "sweet",
      name: "Pan Crema",
      description: "Pan integral con crema de cacahuate, plátano y fresa de temporada.",
      image: "./assets/hotcakes-avena.png",
      price: 50,
    },
    {
      id: "overnight-apple",
      categoryId: "sweet",
      name: "Overnight Oats Apple Pie",
      description:
        "Avena con leche deslactosada, yogurt, vainilla y canela; chía pudding, manzana verde y crema de cacahuate.",
      image: "./assets/apple-pie.png",
      price: 70,
    },
    {
      id: "overnight-choco",
      categoryId: "sweet",
      name: "Overnight Oats Choco Berry",
      description:
        "Avena cremosa con cocoa, fresa, plátano, chocolate líquido y coco rallado.",
      image: "./assets/choco-berry.png",
      price: 70,
    },
    {
      id: "overnight-green",
      categoryId: "sweet",
      name: "Overnight Oats Green Boost",
      description:
        "Avena con matcha orgánico y chía pudding; fresa, plátano, arándanos y granola.",
      image: "./assets/green-boost.png",
      price: 70,
    },

    {
      id: "jugos",
      categoryId: "juices",
      name: "Jugos naturales",
      description: "Elige tu mezcla favorita y el tamaño.",
      image: "./assets/bebidas.png",
      choiceLabel: "Elige tu jugo",
      choices: [
        "Verde Vital",
        "Red Power Boost",
        "Red Fresh",
        "Hierro Power",
        "Sunrise",
        "Antioxidante",
        "Antigripal",
        "Pink Boost",
        "Zana-ranja",
        "Naranja natural",
        "Betabel con naranja",
      ],
      priceOptions: NUTRYFIT_DRINK_SIZES,
    },
    {
      id: "licuados",
      categoryId: "smoothies",
      name: "Licuados",
      description: "Elige una receta o arma tu combinación con frutas, semillas y complementos.",
      image: "./assets/bebidas.png",
      choiceLabel: "Elige tu licuado",
      choices: ["Digestivo", "Mazapán", "Strawberry", "Choco Banana", "Fresa Plátano", "Arma tu licuado"],
      priceOptions: NUTRYFIT_SMOOTHIE_SIZES,
    },

    {
      id: "jamaica",
      categoryId: "drinks",
      name: "Jamaica",
      description: "Jamaica natural endulzada con Splenda.",
      image: "./assets/bebidas.png",
      price: 20,
    },
    {
      id: "limonada-pepino",
      categoryId: "drinks",
      name: "Limonada de pepino con chía",
      description: "Pepino, limón y chía, endulzada con Splenda.",
      image: "./assets/bebidas.png",
      price: 25,
    },
    {
      id: "sparkling",
      categoryId: "drinks",
      name: "Sparkling",
      description: "Bebida carbonatada sin azúcar y sin calorías.",
      image: "./assets/bebidas.png",
      price: 35,
      choiceLabel: "Elige el sabor",
      choices: ["Frambuesa negra", "Fresa-kiwi", "Naranja-mango"],
    },
    {
      id: "limonada-frutos-rojos",
      categoryId: "drinks",
      name: "Limonada natural de frutos rojos",
      description: "Limonada natural con frutos rojos.",
      image: "./assets/bebidas.png",
      priceOptions: [
        { label: "Chica", price: 30 },
        { label: "Grande", price: 50 },
      ],
    },
    {
      id: "coffee",
      categoryId: "drinks",
      name: "Café orgánico con ganoderma",
      description: "Elige entre café negro, café con crema, Cream Coffee o Vita Café.",
      image: "./assets/bebidas.png",
      priceOptions: [
        { label: "Café negro", price: 30 },
        { label: "Café con crema", price: 40 },
        { label: "Cream Coffee", price: 45 },
        { label: "Vita Café", price: 45 },
      ],
    },
  ],
  pokeBuilder: {
    sizes: [
      { id: "small", name: "Chico", grams: "90 g", coldLimit: 3 },
      { id: "medium", name: "Mediano", grams: "150 g", coldLimit: 4 },
      { id: "large", name: "Grande", grams: "210 g", coldLimit: 5 },
    ],
    bases: ["Lechuga orejona", "Arroz", "Quinoa", "Noodles de pepino"],
    proteins: [
      { id: "pollo-mostaza", name: "Pollo mostaza miel", group: 1 },
      { id: "pollo-natural", name: "Pollo natural", group: 1 },
      { id: "pollo-buffalo", name: "Pollo buffalo", group: 1 },
      { id: "tampico", name: "Tampico", group: 1 },
      { id: "atun", name: "Atún", group: 2 },
      { id: "camaron", name: "Camarón", group: 2 },
      { id: "salmon", name: "Salmón", group: 2 },
    ],
    prices: {
      1: { small: 155, medium: 220, large: 270 },
      2: { small: 175, medium: 245, large: 330 },
    },
    coldBar: [
      "Edamames",
      "Panela",
      "Zanahoria",
      "Pimiento",
      "Elote",
      "Brócoli",
      "Manzana verde",
      "Tomate cherry",
      "Espinaca",
      "Champiñón",
      "Cebolla morada",
      "Aguacate",
      "Philadelphia",
      "Mango por temporada",
      "Fresa por temporada",
    ],
    dressings: [
      "Ranch",
      "Chipotle",
      "Mostaza miel",
      "Cilantro serrano",
      "Vinagreta balsámica",
      "Frutos rojos",
      "Spicy mayo",
      "Ponzu",
      "Anguila",
      "Cacahuate oriental",
    ],
    crunch: ["Crutones", "Tiritas de maíz", "Tiritas de wonton", "Cebolla caramelizada"],
    extras: [
      { id: "dressing-extra", name: "Aderezo extra", price: 15 },
      { id: "topping-extra", name: "Topping extra", price: 20 },
      { id: "pollo-extra", name: "Pollo 60 g", price: 25 },
      { id: "tampico-extra", name: "Tampico 60 g", price: 25 },
      { id: "atun-extra", name: "Atún 60 g", price: 45 },
      { id: "camaron-extra", name: "Camarón 60 g", price: 45 },
      { id: "salmon-extra", name: "Salmón 60 g", price: 45 },
    ],
  },
};
